ALTER SESSION SET container = xepdb1;

CREATE USER lock_explorer IDENTIFIED BY "<<DATABASE_PASSWORD>>";

GRANT
    CREATE USER,
    DROP USER,
    ALTER USER,
    SELECT ANY DICTIONARY,
    SELECT ANY TABLE
TO lock_explorer;

GRANT connect,
    CREATE TABLE,
    CREATE SESSION,
    CREATE SEQUENCE,
TO lock_explorer WITH ADMIN OPTION;

ALTER USER lock_explorer
    QUOTA UNLIMITED ON users;