version: "3.9"
services:

  database:
    image: "docker.pkg.github.com/jriegraf/lock-explorer/lock-explorer-database:latest"
    restart: always
    ports:
      - "55500:5500"
      - "51521:1521"
  
  api:
    image: "docker.pkg.github.com/jriegraf/lock-explorer/lock-explorer-api:latest"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - "database"

  frontend:
    image: "docker.pkg.github.com/jriegraf/lock-explorer/lock-explorer-frontend:latest"
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - "api"